In [4]:
import numpy as np
a=np.array([1,2,3])
print(a)


[1 2 3]


In [5]:
a=np.array([1,2,3,4,5,6,7,8,9])
b=a.reshape(3,3)
print(b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
b[2]

array([7, 8, 9])

In [7]:
a[4]


5

In [8]:
a[-2]

8

In [9]:
b[0:,1:]

array([[2, 3],
       [5, 6],
       [8, 9]])

In [10]:
type(a)

numpy.ndarray

In [11]:
np.shape(b)

(3, 3)

In [12]:
np.shape(a)

(9,)

In [13]:
np.ndim(b)

2

In [14]:
np.ndim(a)


1

In [16]:
np.__version__

'1.13.3'

In [18]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [19]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [20]:
a=np.zeros(4,dtype="i").reshape(2,2)
print(a)

[[0 0]
 [0 0]]


In [21]:
import numpy as np
c=np.ones(4,dtype="i").reshape(2,2)
print(c)

[[1 1]
 [1 1]]


In [30]:
import numpy as np
arr1=np.array([2,4,6,8]).reshape(2,2)
print("Matrix 1: \n",arr1)
arr2=np.array([4,2,6,7]).reshape(2,2)
print("Matrix 2: \n",arr2)
arr3=np.dot(arr1,arr2)
print("Matrix multiplied: \n",arr3)

Matrix 1: 
 [[2 4]
 [6 8]]
Matrix 2: 
 [[4 2]
 [6 7]]
Matrix multiplied: 
 [[32 32]
 [72 68]]


In [29]:
import numpy as np
arr1=np.array([2,4,6,8,5,6,3,9,0]).reshape(3,3)
print("Matrix 1: \n",arr1)
arr2=np.array([4,2,6,7,5,7,8,9,5]).reshape(3,3)
print("Matrix 2: \n",arr2)
arr3=np.dot(arr1,arr2)
print("Matrix multiplied: \n",arr3)

Matrix 1: 
 [[2 4 6]
 [8 5 6]
 [3 9 0]]
Matrix 2: 
 [[4 2 6]
 [7 5 7]
 [8 9 5]]
Matrix multiplied: 
 [[ 84  78  70]
 [115  95 113]
 [ 75  51  81]]


In [28]:
import numpy as np
arr1=np.array([2,4,6,8,5,6,3,9,0]).reshape(3,3)
print("Matrix 1: \n",arr1)
arr2=np.array([4,2,6,7,5,7,8,9,5]).reshape(3,3)
print("Matrix 2: \n",arr2)
arr3=np.dot(arr1,arr2)
print("Matrix multiplied: \n",arr3)

trans=np.transpose(arr3)
print("Transpose of matrix:\n",trans)

Matrix 1: 
 [[2 4 6]
 [8 5 6]
 [3 9 0]]
Matrix 2: 
 [[4 2 6]
 [7 5 7]
 [8 9 5]]
Matrix multiplied: 
 [[ 84  78  70]
 [115  95 113]
 [ 75  51  81]]
Transpose of matrix:
 [[ 84 115  75]
 [ 78  95  51]
 [ 70 113  81]]
