In [1]:
#Program to perform svd

import numpy as np
from scipy.linalg import svd

a=np.array([[1,2,3],[4,5,6],[7,8,9]])
print("Matrix :\n",a)

U, s, VT = svd(a)
print("\nU = m*m :\n",U)
print("\ns = m*n :\n",s)
print("\nVT = n*n :\n",VT)

print("\nReconstructing the original matrix :\n",U @ np.diag(s) @ VT)

Matrix :
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

U = m*m :
 [[-0.21483724  0.88723069  0.40824829]
 [-0.52058739  0.24964395 -0.81649658]
 [-0.82633754 -0.38794278  0.40824829]]

s = m*n :
 [  1.68481034e+01   1.06836951e+00   1.47280825e-16]

VT = n*n :
 [[-0.47967118 -0.57236779 -0.66506441]
 [-0.77669099 -0.07568647  0.62531805]
 [ 0.40824829 -0.81649658  0.40824829]]

Reconstructing the original matrix :
 [[ 1.  2.  3.]
 [ 4.  5.  6.]
 [ 7.  8.  9.]]
